# Generated by Django 4.2.10 on 2026-01-01 18:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('article_type', models.CharField(choices=[('product', '产品问题'), ('project', '项目问题'), ('network', '网络管理'), ('device', '设备使用'), ('package', '安装包制作'), ('test', '测试问题'), ('other', '其他')], default='other', max_length=20, verbose_name='问题类型')),
                ('product_version', models.CharField(blank=True, help_text='如：V3.0.1', max_length=100, verbose_name='产品版本')),
                ('project_name', models.CharField(blank=True, help_text='定制项目名称', max_length=100, verbose_name='项目名称')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔，如：网络,故障,紧急', max_length=200, verbose_name='标签')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_resolved', models.BooleanField(default=True, verbose_name='是否解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '知识文章',
                'verbose_name_plural': '知识文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kb.article', verbose_name='所属文章')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='文件')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kb.article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
