# Generated by Django 4.2.10 on 2026-01-01 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_article_comment_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='宿主机名称')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP地址')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宿主机',
                'verbose_name_plural': '宿主机',
            },
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='虚拟机名称')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP地址')),
                ('cpu', models.CharField(max_length=50, verbose_name='CPU配置')),
                ('memory', models.CharField(max_length=50, verbose_name='内存配置')),
                ('disk', models.CharField(max_length=50, verbose_name='磁盘配置')),
                ('os', models.CharField(choices=[('centos7', 'CentOS 7'), ('centos8', 'CentOS 8'), ('ubuntu2004', 'Ubuntu 20.04'), ('ubuntu2204', 'Ubuntu 22.04'), ('windows', 'Windows Server'), ('other', '其他')], max_length=50, verbose_name='操作系统')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='系统版本')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中')], default='running', max_length=20, verbose_name='状态')),
                ('purpose', models.TextField(blank=True, verbose_name='用途描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='kb.hostmachine', verbose_name='所属宿主机')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '虚拟机',
                'verbose_name_plural': '虚拟机',
            },
        ),
    ]
