# Generated by Django 4.2.10 on 2026-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_hostmachine_virtualmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='os',
            field=models.CharField(choices=[('windows', 'Windows Server'), ('麒麟', '麒麟V10_x86'), ('麒麟', '麒麟V10_arm'), ('centos7', 'CentOS 7'), ('centos8', 'CentOS 8'), ('ubuntu', 'Ubuntu'), ('other', '其他')], max_length=50, verbose_name='操作系统'),
        ),
    ]
