# Generated by Django 4.2 on 2026-01-04 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_alter_virtualmachine_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('computer', '电脑'), ('video_terminal', '视频终端'), ('mcu', 'MCU'), ('smc', 'SMC'), ('maxhub', 'MAXHUB'), ('tv', '电视'), ('network_device', '网络设备'), ('storage', '存储设备'), ('other', '其他')], max_length=50, verbose_name='资产类型')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='序列号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, max_length=50, verbose_name='MAC地址')),
                ('configuration', models.TextField(blank=True, help_text='如：CPU、内存、硬盘等配置', verbose_name='配置信息')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='软件版本')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='许可到期时间')),
                ('borrower', models.CharField(blank=True, max_length=100, verbose_name='借货人')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='负责人')),
                ('department', models.CharField(default='交付部', max_length=100, verbose_name='所属部门')),
                ('status', models.CharField(choices=[('in_use', '使用中'), ('idle', '闲置'), ('maintenance', '维护中'), ('retired', '已报废'), ('lent', '已借出')], default='in_use', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='购买价格')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='保修到期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='内容'),
        ),
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='asset_photos/%Y/%m/%d/', verbose_name='照片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='kb.asset', verbose_name='所属资产')),
            ],
            options={
                'verbose_name': '资产照片',
                'verbose_name_plural': '资产照片',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('admin', '管理员'), ('user', '普通用户'), ('security_admin', '安全管理员'), ('sys_admin', '系统管理员'), ('root', 'Root'), ('other', '其他')], max_length=50, verbose_name='凭据类型')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('description', models.CharField(blank=True, help_text='如：默认管理员账户、SSH登录等', max_length=200, verbose_name='描述')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='kb.asset', verbose_name='所属资产')),
            ],
            options={
                'verbose_name': '资产凭据',
                'verbose_name_plural': '资产凭据管理',
                'unique_together': {('asset', 'credential_type', 'username')},
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'status'], name='kb_asset_asset_t_9988ee_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['responsible_person'], name='kb_asset_respons_28f58b_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='kb_asset_serial__1dd86e_idx'),
        ),
    ]
