# Generated by Django 4.2 on 2026-01-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_asset_alter_article_content_assetphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('server', '服务器'), ('computer', '电脑'), ('video_terminal', '视频终端'), ('mcu', 'MCU'), ('smc', 'SMC'), ('maxhub', 'MAXHUB'), ('tv', '电视'), ('network_device', '网络设备'), ('storage', '存储设备'), ('phone', '手机平板'), ('monitor', '显示器'), ('other', '其他')], max_length=50, verbose_name='资产类型'),
        ),
    ]
