# Generated by Django 4.2.11 on 2026-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(max_length=200, verbose_name='文件类型'),
        ),
    ]
