# Generated by Django 4.2.11 on 2026-01-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_alter_attachment_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='os',
            field=models.CharField(choices=[('windows2012', 'Windows Server 2012'), ('windows2016', 'Windows Server 2016'), ('麒麟v10x86', '麒麟V10_x86'), ('麒麟v10arm', '麒麟V10_arm'), ('centos6', 'CentOS 6'), ('centos7', 'CentOS 7'), ('centos8', 'CentOS 8'), ('ubuntu', 'Ubuntu'), ('other', '其他')], max_length=50, verbose_name='操作系统'),
        ),
    ]
