# Generated by Django 4.2.11 on 2026-01-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0013_alter_virtualmachine_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmachine',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='hostmachine',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='用户名'),
        ),
    ]
