# Generated by Django 4.2.11 on 2026-01-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0014_hostmachine_password_hostmachine_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmachine',
            name='port',
            field=models.CharField(blank=True, max_length=20, verbose_name='端口'),
        ),
    ]
