# Generated by Django 4.2.11 on 2026-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0015_hostmachine_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='状态'),
        ),
    ]
