# Generated by Django 4.2.11 on 2026-01-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0016_alter_virtualmachine_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='virtualmachine',
            index=models.Index(fields=['host_machine', 'status'], name='kb_virtualm_host_ma_08d31b_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmachine',
            index=models.Index(fields=['updated_at'], name='kb_virtualm_updated_091594_idx'),
        ),
    ]
