# Generated by Django 4.2.11 on 2026-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0017_virtualmachine_kb_virtualm_host_ma_08d31b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmachine',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间'),
        ),
        migrations.AddField(
            model_name='hostmachine',
            name='status',
            field=models.CharField(choices=[('normal', '运行正常'), ('fault', '运行故障')], default='normal', max_length=20, verbose_name='状态'),
        ),
    ]
