# Generated by Django 4.2.11 on 2026-02-12 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0018_hostmachine_last_check_time_hostmachine_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='包名称')),
                ('package_type', models.CharField(choices=[('java_full', 'Java全量包(pcms.war)'), ('java_incremental', 'Java增量包(pcms.zip)'), ('cpp_program', 'C++程序(pcms)'), ('h5_package', 'H5包(confApp.zip)'), ('java_log_full', 'Java日志全量包(pcmsLog.war)'), ('java_log_incremental', 'Java日志增量包(pcmsLog.zip)')], max_length=30, verbose_name='包类型')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(B)')),
                ('md5_hash', models.CharField(blank=True, max_length=32, verbose_name='MD5校验值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('original_filename', models.CharField(blank=True, max_length=500, verbose_name='原始文件名')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '部署包',
                'verbose_name_plural': '部署包管理',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目代号')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('cpp_install_path', models.CharField(default='/usr/local/PCMS/PCMS', max_length=200, verbose_name='C++程序安装路径')),
                ('java_install_path', models.CharField(default='/usr/local/PCMS/tomcat', max_length=200, verbose_name='Java程序安装路径')),
                ('backup_path', models.CharField(default='/opt/upbak', max_length=200, verbose_name='更新备份文件路径')),
                ('java_port', models.IntegerField(default=80, verbose_name='Java端口')),
                ('cpp_port', models.IntegerField(default=8500, verbose_name='C++端口')),
                ('ssh_timeout', models.IntegerField(default=30, verbose_name='SSH超时时间(秒)')),
                ('health_check_timeout', models.IntegerField(default=30, verbose_name='健康检查超时时间(秒)')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '停用'), ('maintenance', '维护中')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '部署项目',
                'verbose_name_plural': '部署项目管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVMRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_ip', models.CharField(blank=True, help_text='如果为空则使用虚拟机IP，否则使用此IP', max_length=50, verbose_name='覆盖IP地址')),
                ('ssh_username', models.CharField(default='root', max_length=50, verbose_name='SSH用户名')),
                ('ssh_password', models.CharField(blank=True, max_length=200, verbose_name='SSH密码')),
                ('ssh_key_path', models.CharField(blank=True, max_length=200, verbose_name='SSH密钥路径')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.project', verbose_name='项目')),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.virtualmachine', verbose_name='虚拟机')),
            ],
            options={
                'verbose_name': '项目虚拟机关联',
                'verbose_name_plural': '项目虚拟机关联管理',
                'unique_together': {('project', 'virtual_machine')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='virtual_machines',
            field=models.ManyToManyField(through='kb.ProjectVMRelation', to='kb.virtualmachine', verbose_name='关联虚拟机'),
        ),
        migrations.CreateModel(
            name='DeploymentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='任务ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('uploading', '上传文件中'), ('uploaded', '文件上传完成'), ('deploying', '部署中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('log_content', models.TextField(blank=True, verbose_name='日志内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kb.deploymentpackage', verbose_name='部署包')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '部署任务',
                'verbose_name_plural': '部署任务管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务器名称')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP地址')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('ssh_username', models.CharField(max_length=50, verbose_name='SSH用户名')),
                ('ssh_password', models.CharField(blank=True, max_length=200, verbose_name='SSH密码')),
                ('ssh_key_path', models.CharField(blank=True, max_length=200, verbose_name='SSH密钥路径')),
                ('os_type', models.CharField(choices=[('centos', 'CentOS'), ('ubuntu', 'Ubuntu'), ('kylin_v10', '麒麟V10'), ('windows', 'Windows Server'), ('other', '其他')], default='centos', max_length=20, verbose_name='操作系统')),
                ('cpp_install_path', models.CharField(default='/usr/local/PCMS/PCMS', max_length=200, verbose_name='C++程序安装路径')),
                ('java_install_path', models.CharField(default='/usr/local/PCMS/tomcat', max_length=200, verbose_name='Java程序安装路径')),
                ('backup_path', models.CharField(default='/opt/upbak', max_length=200, verbose_name='更新备份路径')),
                ('java_port', models.IntegerField(default=80, verbose_name='Java端口')),
                ('cpp_port', models.IntegerField(default=8500, verbose_name='C++端口')),
                ('is_online', models.BooleanField(default=True, verbose_name='在线状态')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='kb.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '部署服务器',
                'verbose_name_plural': '部署服务器管理',
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='DeploymentScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_script', to='kb.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '部署脚本',
                'verbose_name_plural': '部署脚本管理',
            },
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_version', models.CharField(default='', max_length=50, verbose_name='包版本')),
                ('script_content', models.TextField(blank=True, verbose_name='执行脚本内容')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='部署状态')),
                ('message', models.TextField(blank=True, verbose_name='结果信息')),
                ('java_service_healthy', models.BooleanField(default=False, verbose_name='Java服务正常')),
                ('cpp_service_healthy', models.BooleanField(default=False, verbose_name='C++服务正常')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration', models.IntegerField(default=0, verbose_name='持续时间(秒)')),
                ('project_vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kb.projectvmrelation', verbose_name='项目虚拟机')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.deploymenttask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '部署历史',
                'verbose_name_plural': '部署历史记录',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskServerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_status', models.CharField(default='pending', max_length=20, verbose_name='部署状态')),
                ('deploy_progress', models.IntegerField(default=0, verbose_name='部署进度')),
                ('deploy_log', models.TextField(blank=True, verbose_name='部署日志')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.deploymentserver')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.deploymenttask')),
            ],
            options={
                'unique_together': {('task', 'server')},
            },
        ),
        migrations.CreateModel(
            name='TaskPackageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_status', models.CharField(default='pending', max_length=20, verbose_name='上传状态')),
                ('upload_progress', models.IntegerField(default=0, verbose_name='上传进度')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='上传完成时间')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.deploymentpackage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.deploymenttask')),
            ],
            options={
                'unique_together': {('task', 'package')},
            },
        ),
    ]
